# Generated by Django 4.0.3 on 2022-03-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryBooks', '0002_alter_library_books_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library_books',
            name='availability',
            field=models.CharField(max_length=50),
        ),
    ]
