# Generated by Django 4.0.3 on 2022-03-31 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryBooks', '0004_alter_library_books_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='library_books',
            name='picture',
            field=models.ImageField(default='', upload_to='uploaded_images/'),
        ),
    ]
