# Generated by Django 4.0.3 on 2022-03-31 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryBooks', '0005_library_books_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library_books',
            name='picture',
            field=models.ImageField(default='', upload_to='libraryBooks/uploaded_images/'),
        ),
    ]
