# Generated by Django 4.0.3 on 2022-04-01 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryBooks', '0006_alter_library_books_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library_books',
            name='picture',
        ),
    ]
